<a href="https://colab.research.google.com/github/SergioPedroso/Mestrado-Sistemas-Inteligentes/blob/main/Aula_3_Redes_Neurais_Lab_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Perceptron - Função Lógica AND**

In [ ]:
# Importa a biblioteca numpy para a manipulação de arrays e matrizes, devido à melhor eficiência da bilbioteca
import numpy as np

## DECLARAÇÃO DA FUNÇÃO
# Cria o perceptron
def yperceptron(W,b,X):
  # Calcula a função aditiva, multiplicando a matriz de peso (W) pela matriz de entradas
  u = np.dot(W,X) + b
  # Loop for para percorrer a matriz e aplicar a função de ativação, neste caso sendo a função degrau/limiar
  for i in range(u.shape[1]):
      if u[0, i] >= 0:
          u[0, i] = 1
      else:
          u[0, i] = 0
  return u

## DECLARAÇÃO DAS VARIÁVEIS
# A variável X é a matriz com as entradas do Perceptron
X = np.array([[0,1,0,1],[0,0,1,1]])
print('Número de linhas de X = ',X.shape[0])
print('Número de colunas de X = ',X.shape[1])
# A variável W é a matriz com os pesos do Perceptron
W = np.array([[0.4,0.4]])
# A variável b é o bias, que tem o objetivo variar a influência das entradas
b = -0.6

Número de linhas de X =  2
Número de colunas de X =  4


In [ ]:
# Cálculo da saída do Perceptron
y = yperceptron(W,b,X)
print(y)


[[0. 0. 0. 1.]]


In [ ]:
b

-0.6

In [ ]:
W

array([[0.4, 0.4]])

In [ ]:
X

array([[0, 1, 0, 1],
       [0, 0, 1, 1]])

**Perceptron - Função Lógica OR**

In [ ]:
# Importa a biblioteca numpy para a manipulação de arrays e matrizes, devido à melhor eficiência da bilbioteca
import numpy as np

## DECLARAÇÃO DA FUNÇÃO
# Cria o perceptron
def yperceptron(W,b,X):
  # Calcula a função aditiva, multiplicando a matriz de peso (W) pela matriz de entradas
  u = np.dot(W,X) + b
  # Loop for para percorrer a matriz e aplicar a função de ativação, neste caso sendo a função degrau/limiar
  for i in range(u.shape[1]):
      if u[0, i] >= 0:
          u[0, i] = 1
      else:
          u[0, i] = 0
  return u

## DECLARAÇÃO DAS VARIÁVEIS
# A variável X é a matriz com as entradas do Perceptron
X = np.array([[0,1,0,1],[0,0,1,1]])
print('Número de linhas de X = ',X.shape[0])
print('Número de colunas de X = ',X.shape[1])
# A variável W é a matriz com os pesos do Perceptron
W = np.array([[0.4,0.4]])
# A variável b é o bias, que tem o objetivo variar a influência das entradas
b = -0.2

Número de linhas de X =  2
Número de colunas de X =  4


In [ ]:
# Cálculo da saída do Perceptron
y = yperceptron(W,b,X)
print(y)



[[0. 1. 1. 1.]]


In [ ]:
# Escrever uma conclusão legal, nada de conclusões genéricas (não fazer tipo "tudo funcionou como esperado" kkk)
# Com a aplicação de um perceptron é possível aplicar funções lógicas de forma escalável, ou seja, em um grande volume de dados.